[package]
name = "item-write"
version = "0.1.0"
edition = "2024"

[dependencies]
item-core = { git = "https://github.com/blitzfilter/item-core", rev = "4ddcaff250d695ed89b33b57ad77606dba7a4403" }
tokio = { version = "1", features = ["full"] }
aws-config = { version = "1.6.1"}
aws-sdk-dynamodb = { version = "1.71.1" }
serde_dynamo = { version = "4.2.14", features = ["aws-sdk-dynamodb+1"] }